name: Development (test)

on:
  push

jobs:
  update-db-main:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install bsdtar
      run: sudo apt-get install libarchive-tools
    - name: Install aws
      uses: chrislennon/action-aws-cli@v1.1
    - name: Receiving packages and db
      run: |
        source func.sh
        cd main
        for arch in aarch64 arm i686 x86_64; do
          for i in db files; do
            aws s3api get-object --bucket pacman-main.com --key $arch/main.$i main.$i.tar.gz
          done
          ls
          for i in $(aws s3 ls s3://pacman-main.com/$arch/output/ --recursive | awk '{print $4}'); do
            dir_sp=(${i//// })
            file=${dir_sp[-1]}
            aws s3api get-object --bucket pacman-main.com --key $i $file
            aws s3 mv s3://pacman-main.com/$i s3://pacman-main.com/$arch/
            ./repo-add.sh main.db.tar.gz $file
          done
          rm main.db
          mv main.db.tar.gz main.db
          rm main.files
          mv main.files.tar.gz main.files
          rm main*.old
          for i in db files; do
            aws s3api put-object --bucket pacman-main.com --key $arch/main.$i --body main.$i
          done
          rm main.*
        done
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

