name: Development (test)

on:
  push

jobs:
  update-db-main:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install bsdtar
      run: sudo apt-get install libarchive-tools
    - name: Install aws
      uses: chrislennon/action-aws-cli@v1.1
    - name: Receiving packages and db
      run: |
        source func.sh
        bucket=pacman-main.com
        cd main
        for arch in aarch64 arm i686 x86_64; do
          packages=$(aws-ls $arch/output/)
          if [[ -n $packages ]]; then
            for i in db files; do
              get-object $arch/main.$i main.$i.tar.gz
            done
            for i in $packages; do
              dir_sp=(${i//// })
              file=${dir_sp[-1]}
              name=$(get_name $file)
              for j in $(aws-ls $arch/$name*); do
                dir_sp2=(${j//// })
                if [[ $name = $(get_name ${dir_sp2[-1]}) ]]; then
                  aws-rm $j
                  break
                fi
              done
              get-object $i $file
              aws-mv $i $arch/
              ./repo-add.sh main.db.tar.gz $file
            done
            for i in db files; do
              put-object $arch/main.$i main.$i.tar.gz
            done
            rm main.*
          fi
        done
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

