name: Development (test)

on:
  push

jobs:
  update-db-main:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install aws
      uses: chrislennon/action-aws-cli@v1.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Receiving packages and db
      run: |
        for arch in aarch64 arm i686 x86_64; do
          aws s3 ls s3://pacman-main.com/$arch/output
        done

