name: Development (test)

on:
  push

jobs:
  update-db-main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install aws
      uses: aws-actions/configure-aws-credentials@v1
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Receiving packages and db
      run: |
        for arch in aarch64 arm i686 x86_64; do
          aws s3 ls s3://pacman-main.com/$arch/output
        done

